version: "3.3"
services:
  mongo-container:
    image: mongo
    container_name: mongo-container
    restart: on-failure
    environment:
      MONGO_INITDB_DATABASE: 'caja-dev-mongo'
      MONGO_INITDB_ROOT_USERNAME: 'usr-caja-mongo'
      MONGO_INITDB_ROOT_PASSWORD: 'pwd-caja-mongo'
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro